import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>

        <div>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque
            metus mi, facilisis id augue et, posuere porttitor neque. Duis sed
            condimentum sapien, vel ullamcorper lacus. Interdum et malesuada
            fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet,
            consectetur adipiscing elit. Etiam nec erat ultrices, iaculis quam
            at, elementum lorem. Nullam consectetur quam vitae auctor dictum.
            Proin egestas mollis dignissim. Suspendisse odio augue, faucibus
            quis auctor et, tristique vitae risus. Phasellus faucibus nunc enim,
            ac malesuada diam consectetur vel.
          </p>
          <p>
            Proin sit amet metus nec purus consequat laoreet a nec ipsum. Cras
            sed faucibus felis. Lorem ipsum dolor sit amet, consectetur
            adipiscing elit. Vestibulum pulvinar ut ex nec rhoncus. Cras
            elementum commodo ipsum, a sodales purus lacinia id. Nunc
            sollicitudin diam neque, malesuada condimentum sem rhoncus vitae.
            Maecenas in turpis eu mi maximus congue. Maecenas luctus porta nisl
            non sagittis. Curabitur posuere enim mattis ipsum maximus lacinia.
            Morbi vel tempor eros. Nam condimentum mi ac ipsum suscipit
            tincidunt.
          </p>
          Aenean malesuada erat et sem ornare, ut cursus purus congue. Nunc
          vitae molestie nibh, vel iaculis arcu. Class aptent taciti sociosqu ad
          litora torquent per conubia nostra, per inceptos himenaeos. Ut non
          interdum massa. Vivamus aliquam est eget ipsum luctus, at lacinia
          tellus fermentum. Suspendisse elementum mi rutrum, pulvinar tellus a,
          ultrices metus. Pellentesque efficitur fermentum lobortis. Morbi
          rhoncus mi vitae odio suscipit sodales.
          <p>
            Morbi in rhoncus ipsum. In egestas lectus a risus aliquam, sit amet
            egestas ex dapibus. Vestibulum fringilla lorem in finibus vulputate.
            Donec nisl metus, iaculis non mi sit amet, dignissim eleifend orci.
            Curabitur sed dictum arcu. Suspendisse potenti. Vestibulum id eros
            congue, vulputate diam et, luctus sem. Quisque maximus urna nec
            ipsum sagittis, quis mattis nisl sagittis. Aliquam nec lectus non
            urna ornare facilisis.
          </p>
          <p>
            In accumsan lobortis justo nec accumsan. Fusce id mattis lorem.
            Etiam faucibus in leo eu laoreet. Nulla eu nibh lacus. Lorem ipsum
            dolor sit amet, consectetur adipiscing elit. Curabitur sit amet
            feugiat massa. Curabitur venenatis hendrerit augue, id dignissim
            felis tincidunt tempus. Nulla ut semper lorem. Aenean accumsan
            aliquam purus blandit condimentum. Phasellus ullamcorper et augue ac
            tincidunt. Phasellus at facilisis dui. Etiam tellus nisl, lobortis
            non aliquet eget, malesuada quis tortor. Duis pretium ultrices ante
            non sagittis. Cras est ex, euismod ac mattis ut, dictum eget lectus.
            Sed molestie tincidunt porttitor. Duis eget justo id lorem mattis
            suscipit. Suspendisse non tellus elit. Suspendisse potenti. Maecenas
            erat nunc, volutpat in suscipit ac, ornare interdum nunc. Ut mattis
            erat sit amet quam fermentum, non varius ligula consequat. Curabitur
            imperdiet est pretium eleifend maximus. Maecenas commodo mauris quis
            tristique blandit. Nullam nec pellentesque est. Nam rutrum vulputate
            elit a lobortis. Aenean hendrerit vitae erat sit amet pellentesque.
            Vestibulum viverra vulputate pellentesque. Vestibulum quis tempus
            felis, ac consectetur tellus. Duis accumsan tincidunt magna vel
            placerat. Nam commodo felis sit amet eros sodales sollicitudin.
            Nulla porttitor, augue sit amet congue vestibulum, orci ante
            porttitor risus, id rhoncus libero ipsum at ligula. Pellentesque
            habitant morbi tristique senectus et netus et malesuada fames ac
            turpis egestas. Vivamus porttitor libero cursus justo iaculis, at
            condimentum eros vestibulum. Aenean dignissim eros velit, sed
            elementum orci euismod eget. Suspendisse at massa non nulla pretium
            convallis. Aenean euismod blandit libero id luctus. Integer vehicula
            mollis sem, ac dictum nibh euismod eu. Nullam lacinia a leo luctus
            ornare. Phasellus ac enim ipsum. Donec tempor ornare imperdiet.
            Maecenas blandit a ex eu porta. Donec nisl tortor, molestie
            porttitor risus vitae, venenatis rutrum velit. Aenean nec nibh quam.
            Curabitur eget ultrices eros. Sed scelerisque elit id congue
            egestas. Morbi scelerisque ligula id tortor posuere, a tincidunt
            massa pharetra. Donec interdum, erat sed cursus fermentum, nisi mi
            venenatis orci, tristique vestibulum felis erat vel nibh. Nulla
            facilisi. Nam porta arcu quis felis eleifend, eu feugiat dui
            posuere. Phasellus a placerat felis, vel fringilla tellus. Nulla
            magna eros, porta in leo et, mattis rhoncus est. Aliquam eu odio
            nisl. Integer tempor elit quis augue pharetra, nec aliquam ligula
            sagittis. Nulla in sapien ultricies, ultrices felis at, vehicula
            nibh. Nulla facilisi. Etiam porta mi vel tempor pharetra. Ut nec
            orci sit amet massa volutpat iaculis nec at felis. Nulla et feugiat
            ex. Integer ultricies mauris ipsum, sit amet lacinia ex venenatis
            ac. Etiam nec convallis turpis. Suspendisse mattis convallis tellus
            quis lobortis. Ut magna dui, blandit in aliquam non, rhoncus eget
            lacus. Vivamus efficitur vehicula elit, et sodales leo volutpat vel.
            Nullam accumsan, enim at gravida tempus, lorem orci sodales augue,
            ac varius purus risus sit amet ante. Donec sagittis, urna eu
            molestie dapibus, dui ex commodo ligula, at fringilla lectus tortor
            ut elit. Ut odio orci, consectetur non posuere vitae, porttitor
            vitae elit. Donec varius tincidunt nibh, sit amet lobortis elit
            tempor vitae. Maecenas nibh orci, tempor vel nulla in, cursus
            aliquam risus. Duis et feugiat metus, non ornare lorem. Fusce et
            tellus elit. Proin neque quam, maximus ac dictum malesuada,
            sollicitudin a enim. Nullam ultrices varius sollicitudin. Phasellus
            vestibulum sit amet lectus vel imperdiet. Donec ut metus vulputate
            augue dignissim dignissim ut vel justo. Pellentesque venenatis,
            tellus eu malesuada molestie, dolor dolor convallis elit, sit amet
            luctus eros lectus non tellus. Cras iaculis mattis pretium. Nullam
            auctor odio eget ipsum ornare, aliquet tempus neque accumsan.
            Pellentesque vitae varius elit. Aenean volutpat non lorem sed
            venenatis. Pellentesque ultrices tortor eu lacus gravida volutpat.
            Interdum et malesuada fames ac ante ipsum primis in faucibus.
            Aliquam eleifend cursus leo, sed luctus nibh. Proin urna enim,
            mollis quis nisl sit amet, commodo luctus sem. Proin scelerisque mi
            ut arcu hendrerit cursus non et leo. Sed semper ut massa eget
            tristique. In egestas, odio eu euismod euismod, diam ex congue
            magna, in ornare odio nibh at purus. Donec non tortor rhoncus ante
            mattis consequat quis vel ante. Proin dignissim efficitur maximus.
            Ut est velit, ornare eget vestibulum et, mollis a orci. Aliquam erat
            volutpat. Sed aliquet non lorem vitae sollicitudin. Proin mollis
            iaculis tempus. Phasellus odio ipsum, lobortis sit amet nisi in,
            sagittis convallis tortor. Vestibulum eu risus bibendum eros
            scelerisque malesuada. Praesent eget faucibus dolor. Morbi sit amet
            mi sit amet mi gravida feugiat. Interdum et malesuada fames ac ante
            ipsum primis in faucibus. Etiam ac pretium dolor. Praesent magna
            elit, tempus vitae dolor non, faucibus tincidunt neque. Etiam
            vestibulum pellentesque facilisis. Phasellus ipsum purus, suscipit
            vitae purus ac, euismod ullamcorper mauris. Vivamus varius varius
            turpis id porta. Integer sollicitudin odio a augue tempor aliquet.
            Suspendisse elit ipsum, lobortis eu faucibus quis, vestibulum vel
            diam. Quisque lobortis nulla mi, non sodales metus sollicitudin non.
            Donec ut pretium tellus. Nulla venenatis turpis vel justo gravida
            gravida eget pellentesque mi. Quisque maximus varius finibus.
            Quisque dictum dictum magna. Donec porttitor, ligula eget iaculis
            laoreet, risus enim interdum augue, a dignissim ipsum augue tempus
            tellus. Nunc consequat urna molestie purus elementum fringilla.
            Pellentesque et cursus augue. Curabitur ac mattis tellus. Curabitur
            feugiat sed massa sed vehicula. Pellentesque lacinia metus a nisi
            porta cursus. In eget placerat justo. Nunc sed odio diam. Proin
            auctor enim nec lorem porta volutpat. Vestibulum tincidunt et mi
            quis dictum. Suspendisse lacinia lacus sed quam lacinia, eget
            suscipit nunc lobortis. Vivamus eu consequat magna. Nullam rhoncus
            leo posuere ipsum ultricies ullamcorper. Cras pulvinar erat dolor, a
            sagittis lorem accumsan in. Sed rutrum dolor sit amet sagittis
            tincidunt. Duis non dui hendrerit magna tempor sagittis. Nullam
            elementum magna sit amet arcu maximus, eu varius justo mollis. Proin
            turpis neque, aliquam at massa ut, dignissim condimentum velit. Duis
            erat tortor, sollicitudin vitae felis at, tempus venenatis quam.
            Suspendisse potenti. Fusce arcu neque, accumsan et ornare in, congue
            in purus. Cras eu hendrerit tortor. Integer in ornare lectus.
            Vestibulum commodo nulla id nunc luctus tristique. Nulla vulputate
            faucibus magna, non commodo felis iaculis sit amet. Aliquam interdum
            ultrices risus sed euismod. Nulla id nunc ut elit maximus tristique.
            Maecenas congue consequat dui, nec interdum justo congue sit amet.
            Quisque libero libero, pretium vel diam suscipit, bibendum pretium
            leo. Ut porttitor posuere interdum. Proin leo mi, vestibulum quis
            semper quis, volutpat ac nibh. Sed ac rutrum risus. Proin vitae
            aliquam ante. Curabitur dolor elit, porttitor et consectetur nec,
            sagittis et urna. Vestibulum luctus ultrices ultricies. Integer
            pulvinar, arcu vitae sagittis aliquet, lacus mauris egestas arcu, a
            venenatis eros risus ut quam. Ut a purus purus. Duis eu augue at
            quam mollis tincidunt. Mauris sem orci, vestibulum eu enim at,
            pulvinar commodo metus. Pellentesque habitant morbi tristique
            senectus et netus et malesuada fames ac turpis egestas. Suspendisse
            tempus vehicula enim, blandit bibendum purus sodales eu. Morbi in
            risus tincidunt odio consequat sollicitudin. Donec dapibus imperdiet
            lorem. Ut convallis sapien quis urna consequat, in volutpat lorem
            facilisis. Sed congue lectus quis sapien ultrices, vel auctor tellus
            interdum. Pellentesque molestie nisi in purus aliquam pulvinar. In
            et mi pulvinar mi sagittis consequat eu nec elit. In elementum
            maximus nunc, a pretium ligula sollicitudin quis. Proin nec mauris
            convallis leo laoreet tempor. Aenean congue velit vitae pharetra
            gravida. Sed a tellus id magna viverra commodo. Nam pulvinar ante
            nisl, ac cursus mauris pharetra id. In rhoncus arcu at eros laoreet,
            id lobortis diam tempor. Maecenas faucibus in sapien vitae congue.
            Sed massa ipsum, rhoncus vitae nulla sit amet, vulputate tincidunt
            orci. Cras aliquet lectus nec diam placerat, eget vestibulum erat
            egestas. Etiam quis condimentum sem. Etiam finibus malesuada varius.
            Cras iaculis quam porttitor, rutrum leo sed, consequat sapien. Donec
            in nulla egestas enim iaculis porta. Mauris lorem urna, aliquam eget
            magna quis, efficitur ultrices magna. Curabitur felis erat,
            elementum eget feugiat id, fringilla a purus. Fusce et gravida
            felis, vitae facilisis mauris. Phasellus eget justo eu ante
            malesuada venenatis. Vivamus aliquet nisl in est pharetra suscipit.
            In ultricies congue diam non scelerisque. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
            Nam pharetra eget justo ut iaculis. Sed hendrerit purus eget purus
            pulvinar, at porta odio hendrerit. Phasellus pellentesque suscipit
            ante sagittis efficitur. Donec rutrum mattis sem sit amet lacinia.
            Ut sit amet consequat sapien, a cursus est. Etiam eleifend libero id
            dolor suscipit porta. Morbi eleifend, augue in posuere suscipit,
            lacus libero luctus ex, eu volutpat lectus sapien id odio. Nulla at
            nisl sit amet eros congue varius. Sed imperdiet luctus diam id
            dictum. Donec sed erat at erat gravida volutpat ut vel tortor.
            Aenean vitae augue non eros tristique pulvinar ut nec ex. Aliquam
            convallis augue et dolor tristique vulputate.
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
